spring.application.name=studentapp

spring.datasource.url=${mysql://root:QPpRZxvRcqHZdCRryUXiYECWVJcSsQvZ@centerbeam.proxy.rlwy.net:50307/railway}
spring.datasource.username=${root}
spring.datasource.password=${QPpRZxvRcqHZdCRryUXiYECWVJcSsQvZ}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}